[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
leptos = "0.6"  # or whatever latest
leptos_meta = "0.6"
leptos_router = "0.6"
wasm-bindgen = "0.2"

