# PiMainteno.toml
[llm]
provider = "openai"
api_key = "${OPENAI_API_KEY}"

[cache]
path = "cache"

[scheduler]
enabled = true
cron = "0 2 * * *"
projects = [
 "/media/hamish/pi-storage/Projects/Pi-Maintainer",
 "/media/hamish/pi-storage/Projects/health_web",
 "/media/hamish/pi-storage/Projects/codex/codex-rs"
]

[systemd_monitor]
enabled = true
units = ["nginx.service", "redis.service"]

[web]
host = "0.0.0.0"
port = 8080
